version: "3.8"
services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql-${MYSQL_VERSION}
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis-${REDIS_VERSION}
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "./data/db/redis:/data"
      - "./etc/redis/redis.conf:/etc/redis.conf"
    command: [ "redis-server", "/etc/redis.conf" ]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      #PMA_ARBITRARY: 1 # 是否允许登录外部mysql
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./etc/nginx/conf.d:/etc/nginx/conf.d:ro"
      - "./etc/nginx/ssl:/etc/nginx/ssl:ro"
      - "./logs:/var/log/nginx/"
      - "${LOCAL_DIR}:${DOCKER_DIR}"
    depends_on:
      - mysql
      - redis
      - php-fpm
    command: [ "nginx","-g","daemon off;" ]
  php-fpm:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: killuachen/php-fpm:${PHP_VERSION}
    container_name: php-${PHP_VERSION}
    restart: always
    volumes:
      - "./etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro"
      - "${LOCAL_DIR}:${DOCKER_DIR}"